<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="EC2AMAZ-EC8CRPV" failures="2" tests="5" name="Default test(failed)" time="0.102" errors="0" timestamp="2021-11-21T12:01:33 GMT">
  <testcase classname="demo.TestNGReRunFailedTestsDemo" name="test2" time="0.01">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNGReRunFailedTestsDemo.test2(TestNGReRunFailedTestsDemo.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="demo.TestNGReRunFailedTestsDemo" name="test3" time="0.007">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGReRunFailedTestsDemo" name="test3" time="0.003">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGReRunFailedTestsDemo" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGReRunFailedTestsDemo" name="test3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGReRunFailedTestsDemo.test3(TestNGReRunFailedTestsDemo.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGReRunFailedTestsDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
